### ISSUE TITLE
오타가 있습니다.

### ISSUE THREAD

**Issue by Danue1** [RemoteMonster/browser-sdk#6]
![image](https://user-images.githubusercontent.com/20786911/96304792-b58b8f00-1037-11eb-924f-0c79cf3b1c46.png)

![image](https://user-images.githubusercontent.com/20786911/96304381-f7680580-1036-11eb-9034-03f28f7f229c.png)

**N**avigator.connection을 서버에 로그로 전송하도록 되어 있는데, 네트워크 연결 정보를 저장하고 싶은 것이라면 **n**avigator.connection으로 변경해야 합니다.

추측해보기로는 [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/connection)에서 헷갈릴 수 있는 형태로 문서화를 해놓아서 발생한 '오타' 가 아닌가 싶습니다.

**Comment by Danue1** [comment]
![image](https://user-images.githubusercontent.com/20786911/96347850-69942500-10df-11eb-9739-4552cab9b8ff.png)

비디오 화질이 HIGH인 상태에서 remon.reduceVideoQuality() 메서드를 호출하는 경우 M**I**DIUM으로 다운시키는 문제가 있습니다.

**Comment by calmglow** [comment]
navigator.connection 이슈는 버그가 맞습니다. 아울러 reduceVideoQuality 는 버그가 아닙니다. ^^
감사합니다. 꼭 밥한끼, 소고기, 차 한잔 사드리겠습니다.

**Comment by imyaman** [comment]
@Danue1 큰 도움이 되었습니다. ^_____^

**Comment by Danue1** [comment]
서버측에서 MEDIUM이 아니라 MIDIUM으로 구현 되어 있나 보네요.
살짝 찾아 보고 버그가 아니라는 말씀이 왠지 이해가 되었습니다.

**Comment by imyaman** [comment]
서버가 MEDIUM과 MIDIUM 둘 다 수용하도록 수정하는 걸로 논의 중입니다. 제보 고맙습니다.

**Comment by Danue1** [comment]
@calmglow 
메일 확인 요청 드립니다!
